site_name: "My Library"
docs_dir: .mkdocs
site_dir: docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
  - api-autonav:
      modules:
        - src/modelrepo
